# -*- coding: utf-8 -*-
"""app1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bdDmUV3tNMut9aI8foMOZNd39f_U7LyN
"""

import streamlit as st
import joblib
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download NLTK assets
nltk.download('stopwords')
nltk.download('wordnet')

# Load model and vectorizer
model = joblib.load("logreg_model.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")

# Preprocessing setup
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return ' '.join(tokens)

# Streamlit UI
st.title("🔍 Product Review Sentiment Classifier")
user_input = st.text_area("Enter a product review:")

if st.button("Predict Sentiment"):
    if user_input.strip():
        cleaned = preprocess(user_input)
        transformed = vectorizer.transform([cleaned])
        pred = model.predict(transformed)[0]
        st.write("Prediction:", "👍 Positive" if pred == 1 else "👎 Negative")
    else:
        st.warning("Please enter some text.")